image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-cloud-metrics-relay:
  stage: build
  script:
    - IMAGE_NAME=$CI_REGISTRY_IMAGE/metrics-relay
    - docker pull $IMAGE_NAME:latest || true
    - >-
      docker build --cache-from $CI_REGISTRY_IMAGE:latest 
      --tag $IMAGE_NAME:$CI_COMMIT_SHA 
      --tag $IMAGE_NAME:latest 
      -f ./CloudMetricsRelay/Dockerfile ./CloudMetricsRelay 
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest