apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: pinzberg.kuhn.host
spec:
  secretName: pinzberg-relay-tls
  commonName: pinzberg.kuhn.host
  dnsNames:
    - pinzberg.kuhn.host
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
